#!/usr/bin/env python

from sys import argv
from appscript import *

_help = """osadict help:

    Syntax:

    osadict app-name [help-options ...]


    The app-name argument is the name or full path of the application. 
    
    The help-options arguments are one or more of the following:
        
        -o -- overview of all supported classes and commands

        -k -- all supported application- and AE-defined classes, types,
              enumerators, etc.

        -r [class-name] -- Apple Event Object Model relationships for the
                           application class (default) or the specifed class

        -i [class-name] -- inheritance tree for all classes (default) or the
                           specified class

        -t [class-or-command-name] -- terminology for the application class
                                      (default) or the specified class/command


    Notes:

    If no flags are given, '-o' is used. 

    Values shown in brackets are optional; where none is given, 'application' 
    is used. 

    In a relationships graph (see '-r' option):
        - one-to-one relationships are shown as '-<name>'
        - one-to-many relationships are shown as '=<name>'
        - the property/element's class is shown in parentheses
        - a trailing arrow, '->', indicates a class's structure is already 
          shown elsewhere in the graph

    More extensive interactive help is available from appscript's built-in
    help() method. See the appscript documentation for more information.

    Examples:

        osadict /Applications/TextEdit.app -o -k

        osadict finder -t document_file -i -r disk
"""

#######

if argv[1:]:
    app(unicode(argv[1], 'utf8')).help(' '.join(argv[2:]) or '-o')
else:
    print _help
